[web]
172.31.27.180

[localhost]
localhost

[localhost:vars]
Course = "devops with aws"
Trainer = "manikanta"
Duration = "120hrs"
WISHES = "Morning from inventory"

[db]
172.31.28.238

[app]
172.31.28.239

[all:children]
web
db
app